# Generated by Django 5.0.4 on 2024-05-06 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_remove_job_slug_job_vacancy_job_experience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Vacancy',
            new_name='Availability',
        ),
    ]
