# Generated by Django 5.0.4 on 2024-05-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_apply_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='applied_in',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
