# Generated by Django 5.0.4 on 2024-05-21 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_job_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='owner',
        ),
    ]
