# Generated by Django 5.0.4 on 2024-05-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0023_job_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
